[package]
name = "rust-rvm-vmm"
version = "0.1.0"
authors = ["gjz010 <gjz010944@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rcore-user = {path = "../rust"}
rvm = {path = "../../submodules/RVM"}